### ISSUE TITLE
same unity and aar package name cause error

### ISSUE THREAD

**Issue by flankechen** [mopsicus/native-android-camera-unity#2]
same unity and aar package name would cause unity build error

`stderr[
D8: Program type already present: com.mycompany.images.BuildConfig
java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: com.mycompany.images.BuildConfig
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)`

changing one of them fix this

**Comment by mopsicus** [comment]
yeah, demo is out of date, thx
